### ISSUE TITLE
后端错误，检查网络或者阅读app

### ISSUE THREAD

**Issue by jiangyuhao1996** [sunrishe/legado-vscode#1]
vscode 窗口滚动阅读时，就会显示这条 error 提示
![image](https://github.com/sunrishe/legado-vscode/assets/75724231/0165f38f-b209-4858-aab1-744e2a907b7c)
下面是我的vscode 版本信息
![image](https://github.com/sunrishe/legado-vscode/assets/75724231/ab968e34-abc1-485c-8d3c-605999b1d743)

**Comment by sunrishe** [comment]
我这里可以正常查看，没有复现这种情况诶。
提供一些其他信息，供你参考。OPPO锁屏一小会儿，WEB服务会无法访问，小米手机没有问题的。
