### ISSUE TITLE
增加自定义字体颜色功能

### ISSUE THREAD

**Issue by YongHangPu** [sunrishe/legado-vscode#3]
希望增加自定义字体颜色功能，在暗色主题下，字体颜色太浅。
作者大大牛批，希望有时间更新一下版本。
爱你！！！

**Comment by sunrishe** [comment]
非常感谢你提出的建议，已经采纳，计划稍晚的时间开发并更新上去。

**Comment by sunrishe** [comment]
已发布，请见[v1.4.1](https://github.com/sunrishe/legado-vscode/releases/tag/v1.4.1)
